/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_options_free(a: number): void;
export function __wbg_drawrivers_free(a: number): void;
export function __wbg_generateriverscandidate_free(a: number): void;
export function slime_seed_finder(a: number, b: number): void;
export function river_seed_finder(a: number, b: number, c: number): void;
export function draw_rivers(a: number, b: number): number;
export function generate_rivers_candidate(a: number, b: number): number;
export function count_candidates(a: number, b: number): void;
export function draw_reverse_voronoi(a: number, b: number): void;
export function extend48(a: number, b: number, c: number): void;
export function count_rivers(a: number, b: number, c: number): void;
export function generate_fragment(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function generate_fragment_up_to_layer(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function generate_fragment_slime_map(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function is_i64(a: number, b: number, c: number): void;
export function add_2_n(a: number, b: number, c: number, d: number): void;
export function sub_2_n(a: number, b: number, c: number, d: number): void;
export function gen_test_seed_base_n_bits(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function similar_biome_seed(a: number, b: number, c: number): void;
export function draw_treasure_map(a: number, b: number, c: number): void;
export function treasure_map_seed_finder(a: number, b: number, c: number): void;
export function anvil_region_to_river_seed_finder(a: number, b: number, c: number): void;
export function extract_map_from_screenshot(a: number, b: number, c: number, d: number): number;
export function read_dungeons(a: number, b: number): void;
export function find_blocks_in_world(a: number, b: number, c: number): void;
export function find_block_pattern_in_world(a: number, b: number, c: number): void;
export function find_spawners_in_world(a: number, b: number, c: number): void;
export function nbt_search(a: number, b: number, c: number, d: number): void;
export function get_color_to_biome_map(): number;
export function get_biome_id_to_biome_name_map(): number;
export function read_fragment_biome_map(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function map_fragments_to_png_base64(a: number, b: number, c: number): void;
export function init(): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_start(): void;
