[package]
name = "slime_seed_finder_web"
version = "0.1.0"
authors = ["Badel2 <2badel2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slime_seed_finder = { "path" = ".." }
image = { version = "0.23", default-features = false }
log = { version = "0.4.8", features = ["std"] }
minecraft_screenshot_parser = "0.3"
named-binary-tag = "0.5.0"
palette = "0.5.0"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
stdweb = { git = "https://github.com/Badel2/stdweb", rev = "942dadf9b36df45cb689d52c18753d3d6df4ee9e" }
zip = { version = "0.5.5", default-features = false }
