[package]
name = "slime_seed_finder_web"
version = "0.1.0"
authors = ["Badel2 <2badel2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slime_seed_finder = { "path" = ".." }
ansi_term = "0.12.1"
log = { version = "0.4.8", features = ["std"] }
palette = "0.5.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
stdweb = "0.4.20"
