#!/bin/bash
# Exit script if any command returns non-zero
set -e
set -o pipefail
cd slime_seed_finder_webnode
nj-cli build --release

# TODO: test that the interface generated by slime_seed_finder_webnode is
# compatible with the interface generated by slime_seed_finder_web.
# Maybe use a node script that imports both bindings and compares the exported
# functions by type?
