#!/bin/bash
# Exit script if any command returns non-zero
set -e
set -o pipefail
cargo build --target wasm32-unknown-unknown --release -p slime_seed_finder_web
wasm-bindgen target/wasm32-unknown-unknown/release/slime_seed_finder_web.wasm --out-dir static/ --target no-modules

# Add glue code to make loader generated by wasm_bindgen compatible with the previous one that was
# generated by cargo-web
cat << EOF >> static/slime_seed_finder_web.js
let Rust = {};
Rust.slime_seed_finder_web = wasm_bindgen(
    "./slime_seed_finder_web_bg.wasm"
).then(
    function(unused) {
        return wasm_bindgen;
    },
    function(err) {
        console.error(err);
    }
);
EOF

# Generate local documentation
#cargo doc --features="main"
#cp -rf target/doc target/deploy/doc
