name: Deploy web demo

on:
  push:
    branches:
      - master
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose --features="main"

      - name: Build C bindings
        run: cargo build --verbose -p slime_seed_finder_c

      - name: Run tests
        run: cargo test --verbose --features="main"

      - name: Install cargo-web
        run: ./ci/install_cargo_web.sh

      - name: Build web demo
        run: ./ci/build_demo.sh

      - name: Deploy web demo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
          force_orphan: true
