name: Deploy web demo

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose --features="main"

      - name: Build C bindings
        run: cargo build --verbose -p slime_seed_finder_c

      - name: Run tests
        run: cargo test --verbose --features="main"

      - name: Install nj-cli
        uses: actions-rs/install@v0.1
        with:
          crate: nj-cli
          version: latest

      - name: Build node bindings
        run: ./ci/build_node_bindings.sh

      - name: Install wasm_bindgen
        run: ./ci/install_wasm_bindgen.sh

      - name: Build web demo
        run: ./ci/build_demo.sh

      - name: Deploy web demo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
          force_orphan: true

  publish_electron:
    # Only run this job if this is a tag
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # Do not publish if web demo job fails
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install nj-cli
        uses: actions-rs/install@v0.1
        with:
          crate: nj-cli
          version: latest

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # cd into this directory before running any commands
          package_root: "slime_seed_finder_webui"

          # Command to run before running electron-builder:
          # npm run prepare-dist
          build_script_name: "prepare-dist"
